epochs: 1
num_cycles: 1.0
encoder_lr: 5e-5
decoder_lr: 5e-5
batch_size: 1

min_lr: 1e-6
eps: 1e-6
betas: [0.9, 0.999]
max_len: 512
weight_decay: 0.01
gradient_accumulation_steps: 1
max_grad_norm: 1000
target_cols: ["target"]
seed: 42
n_fold: 5
trn_fold: [0, 1, 2, 3, 4]
train: True
